# Generated by Django 5.0.1 on 2024-02-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtility_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('log_level', models.CharField(max_length=20)),
                ('method_name', models.CharField(max_length=255)),
                ('log_message', models.TextField()),
            ],
            options={
                'db_table': 'youtility_logs',
            },
        ),
    ]
