# Generated by Django 5.0.1 on 2024-02-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0004_alter_error_logs_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='error_logs',
            name='exceptionName',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
